// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sptgrjpeeadysllwhwnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwdGdyanBlZWFkeXNsbHdod25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMjcxMzYsImV4cCI6MjA1NzkwMzEzNn0.gg0JmW5sWQt810Tpf77HHmdx3w_6zHtd3Rd69XxOs6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);